---
title: "Chikv | DE tables and vulcano plots"
author: "Giorgio Gonnella"
date: 2025-06-27
output:
  html_document:
    theme: sandstone
params:
  analysis: "1"
  input_step: "05.P.compute_de"
  input_rds: "so_w_deseq.rds"
  step: "05.V.de_results"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F, warning=F, echo=F)
withr::with_dir(here::here(), { source("renv/activate.R") })

library(Seurat)
library(dplyr)
require(data.table)
library(EnhancedVolcano)

analysis_root <- here::here(paste0("analysis-", params$analysis,"/"))

input_step_dir <- paste0(analysis_root, "steps/", params$input_step, "/")
input_var_dir <- paste0(input_step_dir, "results/vars/")
if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir <- paste0(analysis_root, "steps/", params$step, "/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}

p_adj_filt_tsv_dir <- paste0(this_step_dir, "results/tables/p_adj_filt/")
dir.create(p_adj_filt_tsv_dir, showWarnings = FALSE, recursive = TRUE)
unfiltered_tsv_dir <- paste0(this_step_dir, "results/tables/unfiltered/")
dir.create(unfiltered_tsv_dir, showWarnings = FALSE, recursive = TRUE)
vulcano_outdir <- paste0(this_step_dir, "results/plots/vulcano/")
dir.create(vulcano_outdir, recursive = T, showWarnings = F)
```

```{r load_input_data}
so <- readRDS(file = paste0(input_var_dir, params$input_rds))
```

```{r strsanitize}
strsanitize <- function(s) {
  gsub(" ", "_", gsub("[^[:alnum:]]", "_", s))
}
```

```{r metadata}
lbl <- list()
lbl[["A"]] <- "NC_vs_C"
lbl[["M6"]] <- "NC_vs_C"
lbl[["NC"]] <- "6M_vs_A"
lbl[["C"]] <- "6M_vs_A"
```

```{r plots_and_tables}
for (n in names(so@misc$de)) {
  #print("\n")
  #print(paste0("Results for: ", n, "(", lbl[[n]], ")"))
  #print("\n")
  cond_pairs_lbl <- lbl[[n]]
  celltypes <- names(so@misc$de[[n]]$pval_filt)
  for (ct in celltypes) {
    #print(paste0("- Celltype: ", ct))
    #print("\n")
    data <- so@misc$de[[n]]$pval_filt[[ct]]
    fname <- paste0(vulcano_outdir, n, ".", cond_pairs_lbl, ".",
                    strsanitize(ct), ".png")
    if (!is.null(data)) {
      if (nrow(data) > 0) {
        plt <- EnhancedVolcano(data, lab = rownames(data),
                               x = 'avg_log2FC', y = 'p_val_adj',
                               FCcutoff = 0.58, pCutoff = 0.05) +
          ggtitle(paste0(n, " | ", cond_pairs_lbl, " | ", ct))
        #print("\n")
        #print(paste0("  Writing file: ", fname))
        #print("\n")
        ggsave(fname, plt, width = 7, height = 5)
        print(plt)
        #print("\n")
      }
    }
    fname <- paste0(p_adj_filt_tsv_dir, n, ".", cond_pairs_lbl, ".",
                    strsanitize(ct), ".tsv")
    if (!is.null(data)) {
      if (nrow(data) > 0) {
        # Add metadata columns
        data$cmp <- cond_pairs_lbl
        data$ct <- ct
        data$gene <- rownames(data)

        # Reorder columns to match desired output format
        output <- data[, c("cmp", "ct", "gene", "pct.1", "pct.2",
                           "p_val", "p_val_adj", "avg_log2FC")]

        # Write the data to file
        #print("\n")
        #print(paste0("  Writing file: ", fname))
        #print("\n")
        fwrite(output, file = fname, sep = "\t", quote = FALSE)
      }
    }
  }
  celltypes <- names(so@misc$de[[n]]$all)
  for (ct in celltypes) {
    #print(paste0("- Celltype: ", ct))
    #print("\n")
    data <- so@misc$de[[n]]$all[[ct]]
    fname <- paste0(unfiltered_tsv_dir, n, ".", cond_pairs_lbl, ".",
                    strsanitize(ct), ".tsv")
    if (!is.null(data)) {
      if (nrow(data) > 0) {
        # Add metadata columns
        data$cmp <- cond_pairs_lbl
        data$ct <- ct
        data$gene <- rownames(data)

        # Reorder columns to match desired output format
        output <- data[, c("cmp", "ct", "gene", "pct.1", "pct.2",
                           "p_val", "p_val_adj", "avg_log2FC")]

        # Write the data to file
        #print("\n")
        #print(paste0("  Writing file: ", fname))
        #print("\n")
        fwrite(output, file = fname, sep = "\t", quote = FALSE)
      }
    }
  }
}
```

# Session info

```{r}
sessionInfo()
```

