---
title: "`r paste(c(params$report_title_prefix, 'CellChat circle plots', if (params$pair %in% names(params$pair_labels)) params$pair_labels[[params$pair]] else params$pair, if (params$sfx %in% names(params$filter_labels)) params$filter_labels[[params$sfx]] else params$sfx), collapse = ' | ')`"
author: "`r params$author`"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: sandstone
params:
  input_rds: "../../07.P.compute_cellchat/results/vars/so_w_cellchat.rds"
  author: "Giorgio Gonnella"
  pair: "A_C_vs_NC"
  sfx:  "pfilt"
  filter_mode: "pfilt"
  pval_threshold: 0.05
  output_dir: "../results"
  output_href_prefix: "../results"
  pair_definitions: !r list(A_C_vs_NC = c("A_C", "A_NC"), `6m_C_vs_NC` = c("6m_C", "6m_NC"), NC_A_vs_6m = c("A_NC", "6m_NC"), C_A_vs_6m = c("A_C", "6m_C"))
  pair_labels: !r list(A_C_vs_NC = "Acute - Chronic vs Non-Chronic", `6m_C_vs_NC` = "6 months - Chronic vs Non-Chronic", NC_A_vs_6m = "Non-Chronic - Acute vs 6 months", C_A_vs_6m = "Chronic - Acute vs 6 months")
  filter_labels: !r list(all = "unfiltered", pfilt = "p-value filtered")
  report_title_prefix: "Chikv"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)

library(baia.cellchat)
library(Seurat)
library(CellChat)
library(rmdreportdeck)
reportdeck_setup()
knitr::opts_chunk$set(cache=F)

if (is.null(params$sfx) || !nzchar(params$sfx)) params$sfx <- params$filter_mode
if (is.null(params$pair_definitions))
  stop("Pass pair_definitions to rmarkdown::render().", call. = FALSE)
if (!params$pair %in% names(params$pair_definitions)) stop("Unknown pair: ", params$pair)
if (!params$sfx  %in% c("all", "pfilt")) stop("Unknown sfx: ", params$sfx)

conds  <- params$pair_definitions[[params$pair]]
nm1    <- conds[1]; nm2 <- conds[2]
sfx    <- params$sfx
thresh <- if (sfx == "pfilt") params$pval_threshold else 1
pfx    <- paste0(params$pair, ".", sfx)

plots_outdir <- file.path(params$output_dir, params$pair, sfx, "plots")
dir.create(plots_outdir, recursive = TRUE, showWarnings = FALSE)
```

# Goal

Visualize CellChat ligand–receptor signaling as circle plots for a given condition pair and
filter setting. Each panel shows the aggregated communication network (by pathway) for one
condition, rendered as a chord diagram with cell types as nodes.

```{r load_so}
so <- readRDS(file = params$input_rds)
cc <- so@misc$cellchat_filtered[[sfx]]
```

```{r circle, results='asis'}
baia.cellchat::cellchat_results_circle_section(
  cc = cc, nm1 = nm1, nm2 = nm2, sfx = sfx, thresh = thresh,
  pfx = pfx, plots_outdir = plots_outdir, params = params
)
```

# Session info

```{r session_info, echo=FALSE}
sessionInfo()
```
