---
title: "Chikv | CellChat results"
author: "Giorgio Gonnella"
date: 2025-11-28
output:
  html_document:
    theme: sandstone
params:
  analysis: "1"
  input_step: "07.P.compute_cellchat"
  input_rds: "so_w_cellchat.rds"
  this_step: "07.V.cellchat_results"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)
withr::with_dir(here::here(), { source("renv/activate.R") })

library(Seurat)
library(CellChat)
library(patchwork)

analysis_root <- here::here(paste0("analysis-", params$analysis,"/"))

input_step_dir <- paste0(analysis_root, "steps/", params$input_step, "/")
input_var_dir  <- paste0(input_step_dir, "results/vars/")

if (!dir.exists(input_var_dir)) {
  stop("Input variable directory does not exist: ", input_var_dir)
}

this_step_dir  <- paste0(analysis_root, "steps/", params$this_step, "/")
if (!dir.exists(this_step_dir)) {
  stop("Current step directory does not exist: ", this_step_dir)
}

plots_outdir <- paste0(this_step_dir, "results/plots/")
if (!dir.exists(plots_outdir)) {
  dir.create(plots_outdir, recursive = TRUE)
}
```

```{r load_so}
so <- readRDS(file = paste0(input_var_dir, params$input_rds))
cc_A  <- so@misc$cellchat$A
cc_6m <- so@misc$cellchat$`6m`
cc_NC <- so@misc$cellchat$NC
cc_C  <- so@misc$cellchat$C
```

```{r merge}
merge_two_cellchat <- function(cc1, cc2, names) {
  object.list <- setNames(list(cc1, cc2), names)
  merged      <- mergeCellChat(object.list, add.names = names(object.list))
  merged
}

cc_A_6m <- merge_two_cellchat(cc_A, cc_6m, c("A", "6m"))
cc_NC_C <- merge_two_cellchat(cc_NC, cc_C, c("NC", "C"))
```

```{r circle_plots_separated}
for (cc_name in c("A", "6m", "NC", "C")) {
  cc <- get(paste0("cc_", cc_name))
  print(cc_name)
  all_pathways <- cc@netP$pathways
  outdir <- file.path(plots_outdir, "circle", cc_name)
  dir.create(outdir, showWarnings = F, recursive = T)
  for (pathway in all_pathways) {
    print(pathway)
    plt <- netVisual_aggregate(cc, signaling  = pathway,
      layout = "circle")
    title(paste0(cc_name, ": ", pathway))
    plt <- recordPlot()
    pdf(output_file <- file.path(outdir,
      paste0(cc_name, "_", gsub(" ", "_", pathway), "_circle.pdf")),
      width=9, height=9)
    replayPlot(plt)
    dev.off()
  }
}
```

```{r index_cell_groups}
idx <- list()
idx[["B_cells"]] <- c(1,2,3,4,5)
idx[["CD4_T_cells"]] <- c(6,7,8,9,10,11,12,13)
idx[["CD8_T_cells"]] <- c(14,15,16,17)
idx[["GD_T_cells"]] <- c(18,19)
idx[["Dendritic_cells"]] <- c(22,23)
idx[["Monocytes"]] <- c(24,25,26)
idx[["Other_cells"]] <- c(20, 21, 27)
```

```{r merge_cell_groups}
group.celltype = c(rep("B cells", 5),
                   rep("CD4+ T cells", 8),
                   rep("CD8+ T cells", 4),
                   rep("GD T cells", 2),
                   rep("MAIT cells", 1),
                   rep("NK cells", 1),
                   rep("Dendritic cells", 2),
                   rep("Monocytes", 3),
                   rep("Progenitor cells", 1))
cc_A_g = mergeInteractions(cc_A, group.celltype)
cc_6m_g = mergeInteractions(cc_6m, group.celltype)
cc_NC_g = mergeInteractions(cc_NC, group.celltype)
cc_C_g = mergeInteractions(cc_C, group.celltype)
cc_A_6m_g <- merge_two_cellchat(cc_A_g, cc_6m_g, c("A", "6m"))
cc_NC_C_g <- merge_two_cellchat(cc_NC_g, cc_C_g, c("NC", "C"))
```

```{r hierarchy_plots_separated}
for (cc_name in c("A", "6m", "NC", "C")) {
  cc <- get(paste0("cc_", cc_name))
  print(cc_name)
  all_pathways <- cc@netP$pathways
  outdir <- file.path(plots_outdir, "hierarchy", cc_name)
  dir.create(outdir, showWarnings = F, recursive = T)
  for (pathway in all_pathways) {
    print(pathway)
    for (cg in names(idx)) {
      print(cg)
      plt <- netVisual_aggregate(cc, signaling  = pathway,
        layout = "hierarchy", vertex.receiver = idx[[cg]],
        vertex.weight = 5, show.legend=T, vertex.label.cex = 0.6, point.size = 0.3, scale=T, big.gap=15, small.gap=2)
      title(paste0(cc_name, ": ", pathway, " - ", cg))
      plt <- recordPlot()
      pdf(output_file <- file.path(outdir,
        paste0(cc_name, "_", gsub(" ", "_", pathway), "_receiver_", cg, "_hierarchy.pdf")),
        width=9, height=12)
      replayPlot(plt)
      dev.off()
    }
  }
}
```
```{r chord_plots_separated}
for (cc_name in c("A", "6m", "NC", "C")) {
  cc <- get(paste0("cc_", cc_name))
  print(cc_name)
  all_pathways <- cc@netP$pathways
  outdir <- file.path(plots_outdir, "chord", cc_name)
  dir.create(outdir, showWarnings = F, recursive = T)
  for (pathway in all_pathways) {
    pdf(output_file <- file.path(outdir,
      paste0(cc_name, "_", gsub(" ", "_", pathway), "_chord.pdf")),
      width=5, height=5)
    #replayPlot(plt)
    circos.clear()
    circos.par(
  canvas.xlim = c(-1, 1),
  canvas.ylim = c(-1, 1)
  # and other options if needed
)
    print(pathway)
    plt <- netVisual_aggregate(cc, signaling  = pathway,
      layout = "chord", vertex.label.cex = 0.25, vertex.weight=2,
      signaling.name = paste0(cc_name, ": ", pathway))
    #plt <- recordPlot()
    dev.off()
  }
}
```

```{r merged}
for (cc in c(cc_A_6m, cc_NC_C)) {
  print(cc)
  all_pathways <- cc@netP$pathways
  print(all_pathways)
  # Comparing the total number of interactions
  gg1 <- compareInteractions(cc, show.legend = F, group = c(1,2))
  print(gg1)
  # Comparing the total interaction strength
  gg2 <- compareInteractions(cc, show.legend = F, group = c(1,2), measure="weight")
  print(gg2)
  # Examine the differential number of interactions
  netVisual_diffInteraction(cc, weight.scale = T)
  # Examine the differential interaction strengths
  netVisual_diffInteraction(cc, weight.scale = T, measure = "weight")
  # heatmap of differential number of interactions
  netVisual_heatmap(cc)
  # heatmap of differential interaction strengths
  netVisual_heatmap(cc, measure = "weight")


#  for (pathway in all_pathways) {
#    plt <- netVisual_aggregate(cc, signaling  = pathway,
#      layout = "circle", comparison = c(1, 2), show.legend = T,
#      pt.title=13)
#    print(plt)
#  }
}
```

```{r merged_cell_groups}
#par(mfrow=c(1,2), xpd=TRUE)
object.list = list(cc_A_6m_g, cc_NC_C_g)
for (cc in c(cc_A_6m_g, cc_NC_C_g)) {
  netVisual_diffInteraction(cc, weight.scale = T, measure = "count.merged")
}
num.link <- sapply(object.list, function(x) {rowSums(x@net$count) + colSums(x@net$count)-diag(x@net$count)})
weight.MinMax <- c(min(num.link), max(num.link)
  
```

```{r, eval=F}
# 1) Overall interaction counts and weights
p_counts_A6m  <- compareInteractions(cellchat_A_6m, show.legend = TRUE, group = "datasets")
p_weights_A6m <- compareInteractions(cellchat_A_6m, show.legend = TRUE,
                                     group = "datasets", measure = "weight")

p_interactions_A6m <- p_counts_A6m + p_weights_A6m
print(p_interactions_A6m)

ggsave(
  filename = file.path(plots_outdir, "A_vs_6m_interactions.png"),
  plot     = p_interactions_A6m,
  width    = 10, height = 4, dpi = 300
)

# 2) Signaling role scatter
#p_scatter_A6m <- netAnalysis_signalingRole_scatter(cellchat_A_6m)
#print(p_scatter_A6m)

#ggsave(
#  filename = file.path(plots_outdir, "A_vs_6m_signalingRole_scatter.png"),
#  plot     = p_scatter_A6m,
#  width    = 6, height = 5, dpi = 300
#)

# 3) Example pathway circle plot
pathway_A6m <- get_example_pathway(cellchat_A_6m)

if (!is.na(pathway_A6m)) {
  p_pathway_A6m <- netVisual_aggregate(
    cellchat_A_6m,
    signaling  = pathway_A6m,
    layout     = "circle",
    comparison = c(1, 2)
  )
  print(p_pathway_A6m)

  ggsave(
    filename = file.path(plots_outdir, paste0("A_vs_6m_", pathway_A6m, "_circle.png")),
    plot     = p_pathway_A6m,
    width    = 9, height = 4, dpi = 300
  )
}

# 4) Bubble plot (LR pairs)
p_bubble_A6m <- netVisual_bubble(
  cellchat_A_6m,
  remove.isolate = FALSE,
  comparison     = c(1, 2),
  angle.x        = 45
)
print(p_bubble_A6m)

ggsave(
  filename = file.path(plots_outdir, "A_vs_6m_bubble.png"),
  plot     = p_bubble_A6m,
  width    = 10, height = 5, dpi = 300
)
```

```{r NC_vs_C, eval=F}
cellchat_NC_C <- merge_two_cellchat(cc_NC, cc_C, c("NC", "C"))

# 1) Overall interaction counts and weights
p_counts_NCC  <- compareInteractions(cellchat_NC_C, show.legend = TRUE,
                                     group = "datasets")
p_weights_NCC <- compareInteractions(cellchat_NC_C, show.legend = TRUE,
                                     group = "datasets", measure = "weight")

p_interactions_NCC <- p_counts_NCC + p_weights_NCC
print(p_interactions_NCC)

ggsave(
  filename = file.path(plots_outdir, "NC_vs_C_interactions.png"),
  plot     = p_interactions_NCC,
  width    = 10, height = 4, dpi = 300
)

# 2) Signaling role scatter
#p_scatter_NCC <- netAnalysis_signalingRole_scatter(cellchat_NC_C)
#print(p_scatter_NCC)

#ggsave(
#  filename = file.path(plots_outdir, "NC_vs_C_signalingRole_scatter.png"),
#  plot     = p_scatter_NCC,
#  width    = 6, height = 5, dpi = 300
#)

# 3) Example pathway circle plot
pathway_NCC <- get_example_pathway(cellchat_NC_C)

if (!is.na(pathway_NCC)) {
  p_pathway_NCC <- netVisual_aggregate(
    cellchat_NC_C,
    signaling  = pathway_NCC,
    layout     = "circle",
    comparison = c(1, 2)
  )
  print(p_pathway_NCC)

  ggsave(
    filename = file.path(plots_outdir,
                         paste0("NC_vs_C_", pathway_NCC, "_circle.png")),
    plot     = p_pathway_NCC,
    width    = 9, height = 4, dpi = 300
  )
}

# 4) Bubble plot
p_bubble_NCC <- netVisual_bubble(
  cellchat_NC_C,
  remove.isolate = FALSE,
  comparison     = c(1, 2),
  angle.x        = 45
)
print(p_bubble_NCC)

ggsave(
  filename = file.path(plots_outdir, "NC_vs_C_bubble.png"),
  plot     = p_bubble_NCC,
  width    = 10, height = 5, dpi = 300
)

```

## Session info

```{r, echo=F}
sessionInfo()
```
